apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tkgs1-spring-dev-team-k8s-2
  namespace: spring-dev-team-ns
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: guaranteed-small
      storageClass: tanzu-disk-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
    nodePools:
    - name: worker-nodepool-a1
      replicas: 1
      vmClass: guaranteed-small
      storageClass: tanzu-disk-storage-policy
      tkr:  
        reference:
          name: v1.21.2---vmware.1-tkg.1.ee25d55
settings:
    network:
      cni:
        name: antrea
      services:
        cidrBlocks: ["198.53.100.0/16"]
      pods:
        cidrBlocks: ["192.0.5.0/16"]
